package com.cnh.dataobject;

public class Trophy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trophy.id
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trophy.name
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trophy.content
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trophy.level
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trophy.id
     *
     * @return the value of tb_trophy.id
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trophy.id
     *
     * @param id the value for tb_trophy.id
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trophy.name
     *
     * @return the value of tb_trophy.name
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trophy.name
     *
     * @param name the value for tb_trophy.name
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trophy.content
     *
     * @return the value of tb_trophy.content
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trophy.content
     *
     * @param content the value for tb_trophy.content
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trophy.level
     *
     * @return the value of tb_trophy.level
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trophy.level
     *
     * @param level the value for tb_trophy.level
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}