package com.cnh.dao;

import com.cnh.dataobject.RandomCode;
import com.cnh.dto.UserInformation;
import com.cnh.vo.UserforAdminVo;
import com.cnh.vo.UserforUserVo;
import com.github.pagehelper.Page;
import com.github.pagehelper.PageInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

@Mapper
public interface RandomCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_redom_code
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_redom_code
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    int insert(RandomCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_redom_code
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    int insertSelective(RandomCode record);


    /**
     * 批量添加
     */
int insertList(List<RandomCode> randomCodes);


/**
 * 分页条件查找,在dao层的时候条件是map
 */
    /**
     * 这个是ajax查询的，但是form表单传进来的值不能做成一个对象,这次屏蔽
     * @param map
     * @return
     */
 List<UserforAdminVo>  findAllCodeByPage(Map<String, Object> map);

    /**
     * 这个直接用传进来的值做的
     * @param phone
     * @return
     */
    List<UserforAdminVo>  findAllCodeByPageForm(@Param("trophy") int trophy,@Param("used") int used,@Param("sendGoods") int sendGoods);


List<UserforUserVo> findByPhone(String phone);


/**
 * 查找根据codema
 */
RandomCode findByCode(String codeText);


/**
 * 更新这个random表，同时去新增address表
 *
 */

/*int updateByCode(String random, int addressId);*/


int updateByCode(RandomCode randomCode);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_redom_code
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    RandomCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_redom_code
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    int updateByPrimaryKeySelective(RandomCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_redom_code
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    int updateByPrimaryKey(RandomCode record);
}