package com.cnh.dao;

import com.cnh.dataobject.Trophy;

public interface TrophyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trophy
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trophy
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    int insert(Trophy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trophy
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    int insertSelective(Trophy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trophy
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    Trophy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trophy
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    int updateByPrimaryKeySelective(Trophy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trophy
     *
     * @mbggenerated Fri Aug 16 10:07:20 CST 2019
     */
    int updateByPrimaryKey(Trophy record);
}